kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-pv 
provisioner:  kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-2a, us-east-2b
  iopsPerGB: "10"
  fsType: ext4
 

